// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminCalendar: typeof import('./views/AdminCalendar.vue')['default']
    AdminCertificates: typeof import('./views/AdminCertificates.vue')['default']
    AdminDashboard: typeof import('./views/AdminDashboard.vue')['default']
    AdminDashboardItem: typeof import('./common/components/AdminDashboardItem.vue')['default']
    AdminGroups: typeof import('./views/AdminGroups.vue')['default']
    AdministradorDashboard: typeof import('./views/AdministradorDashboard.vue')['default']
    AdminPrograms: typeof import('./views/AdminPrograms.vue')['default']
    AdminQDrawer: typeof import('./common/components/AdminQDrawer.vue')['default']
    AdminRequests: typeof import('./views/AdminRequests.vue')['default']
    AdminSettings: typeof import('./views/AdminSettings.vue')['default']
    AdminStudents: typeof import('./views/AdminStudents.vue')['default']
    copy: typeof import('./common/components/AdminPrograms.vue')['default']
    HelloWorld: typeof import('./common/components/HelloWorld.vue')['default']
    Login: typeof import('./views/Login.vue')['default']
    PasswordRecovery: typeof import('./views/PasswordRecovery.vue')['default']
    QHeader: typeof import('./common/components/QHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
